### ISSUE TITLE
[Request] Light version of minimal nord wallpapers

### ISSUE THREAD

**Issue by shaunsingh** [maisoncastro/Nord-UI#1]
Hi, was wondering if its possible to make these wallpapers but with a light color in the background (and dark as the foreground?

![](https://user-images.githubusercontent.com/12770284/136597182-b029954a-7a04-4a66-bc11-5aa03bff84b7.png)

**Comment by maisoncastro** [comment]
Definitely! I'll make a few variations today, so keep your eyes peeled!

**Comment by maisoncastro** [comment]
Pillar and Minimal series have been updated. Enjoy!
